vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        dish_images:
            uri_prefix: /images/dishes
            upload_destination: '%kernel.project_dir%/public/images/dishes'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true